disabled_rules: # rule identifiers to exclude from running
  - file_length
  # - force_cast
  - function_body_length
  - line_length
  # - return_arrow_whitespace
  # - todo
  # - type_body_length
  # - type_name
  - variable_name
  - conditional_binding_cascade # re-enable once SwiftLint gets it right for Swift 3?
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  # - Source
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - Constants

file_length:
  warning: 450
  error: 500

statement_position:
  statement_mode: uncuddled_else
