disabled_rules: # rule identifiers to exclude from running
  - file_length
  - function_body_length
  - line_length
  - variable_name

enabled_rules:
  - vertical_whitespace
  - operator_usage_whitespace

excluded:
  - Carthage
  - Pods
  - Constants
  - Screenshots/SnapshotHelper.swift

file_length:
  warning: 450
  error: 500

statement_position:
  statement_mode: uncuddled_else

trailing_comma:
    mandatory_comma: true
